service: nh

plugins:
  - serverless-pseudo-parameters
  - serverless-stack-output

provider:
  name: aws
  runtime: go1.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    SNS_TOPIC: "arn:aws:sns:us-east-1:#{AWS::AccountId}:${self:service}-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "${self:provider.environment.SNS_TOPIC}"

package:
 exclude:
   - ./**
 include:
   - ./bin/nh-**

functions:
  poll:
    handler: bin/nh-poll
    events:
      - schedule: rate(10 minutes)
  slack:
    handler: bin/nh-slack
    events:
      - http:
          path: /slack/{channel}/{token0}/{token1}/{token2}
          method: POST

resources:
  Resources:
    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: aws-status
        TopicName: "${self:service}-${opt:stage, self:provider.stage}"
    ItemsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: guid
            AttributeType: S
        KeySchema:
          - AttributeName: guid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        TimeToLiveSpecification:
          AttributeName: date_time
          Enabled: true

custom:
  output:
    file: stack.json